.TH "CHECKSAME" "1" "January 2021" "CheckSame v0.1.6" "User Commands"
.SH NAME
CheckSame \- Manual page for checksame v0.1.6.
.SH DESCRIPTION
CheckSame generates a single Blake3 hash from any number of files or directories.
.SS USAGE:
.TP
checksame [FLAGS] [OPTIONS] <PATH(s)…>
.SS FLAGS:
.TP
\fB\-c\fR, \fB\-\-cache\fR
Cache the hash and output the status.
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help information.
.TP
\fB\-\-reset\fR
Reset any previously\-saved hash keys before starting.
.TP
\fB\-V\fR, \fB\-\-version\fR
Print program version.
.SS OPTIONS:
.TP
\fB\-l\fR, \fB\-\-list\fR <FILE>
Read file paths from this text file.
.SS <PATH(S)…>:
.TP
Any number of files and directories to crawl and crunch.
.SH OUTPUT
By default, this will print a single 64\-character Blake3 hash for the file(s) to STDOUT.
.RE
In \-\-cache mode, the hash will be cached and compared against the previous run. A value of \-1, 0, or 1 will be printed instead, indicating NEW, UNCHANGED, or CHANGED, respectively.
